//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoleplayJogo.Database
{
    using System;
    using System.Collections.Generic;
    
    using RoleplayJogo.Database.Core;
    
    public partial class AttSkillCategoria : IBaseClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AttSkillCategoria()
        {
            this.AttSkill = new HashSet<AttSkill>();
        }
    
        public long ID { get; set; }
        public string ASC_DESCRICAO { get; set; }
        public Nullable<bool> ASC_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttSkill> AttSkill { get; set; }
    }
}
