//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoleplayJogo.Database
{
    using System;
    using System.Collections.Generic;
    
    using RoleplayJogo.Database.Core;
    
    public partial class AttSkill : IBaseClass
    {
        public long ID { get; set; }
        public Nullable<long> ATT_SAL_ID { get; set; }
        public Nullable<long> ATT_USU_ID { get; set; }
        public string ATT_NOME { get; set; }
        public string ATT_ABREVIACAO { get; set; }
        public string ATT_DESCRICAO { get; set; }
        public string ATT_NOTACAO { get; set; }
        public Nullable<bool> ATT_ATIVO { get; set; }
        public Nullable<System.DateTime> ATT_DATA_CRIACAO { get; set; }
        public Nullable<long> ATT_ASC_ID { get; set; }
    
        public virtual Sala Sala { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual AttSkillCategoria AttSkillCategoria { get; set; }
    }
}
