//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoleplayJogo.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RoleplayJogoEntities : DbContext
    {
        public RoleplayJogoEntities()
            : base("name=RoleplayJogoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttSkill> TBL_ATTSKILL { get; set; }
        public virtual DbSet<Sala> TBL_SALA { get; set; }
        public virtual DbSet<Usuario> TBL_USUARIO { get; set; }
        public virtual DbSet<AttSkillCategoria> TBL_ATTSKILL_CATEGORIA { get; set; }
        public virtual DbSet<Ficha> TBL_FICHA { get; set; }
        public virtual DbSet<TipoUsuario> TBL_TIPO_USUARIO { get; set; }
    }
}
