//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoleplayJogo.Database
{
    using System;
    using System.Collections.Generic;
    
    using RoleplayJogo.Database.Core;
    
    public partial class Usuario : IBaseClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.AttSkill = new HashSet<AttSkill>();
            this.Sala = new HashSet<Sala>();
            this.Ficha = new HashSet<Ficha>();
        }
    
        public long ID { get; set; }
        public string USU_LOGIN { get; set; }
        public string USU_SENHA { get; set; }
        public string USU_EMAIL { get; set; }
        public string USU_NOME { get; set; }
        public string USU_SOBRENOME { get; set; }
        public Nullable<System.DateTime> USU_DATA_NASCIMENTO { get; set; }
        public Nullable<bool> USU_VERIFICADO { get; set; }
        public Nullable<bool> USU_ATIVO { get; set; }
        public Nullable<System.DateTime> USU_DATA_CRIACAO { get; set; }
        public Nullable<System.DateTime> USU_DATA_VERIFICACAO { get; set; }
        public Nullable<long> USU_TPO_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttSkill> AttSkill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sala> Sala { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ficha> Ficha { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
